### ISSUE TITLE
Darwincore checklist dataset version?

### ISSUE THREAD

**Issue by abubelinha** [idiv-biodiversity/LCP#2]
Not an issue, but a question:

Very useful checklist, indeed.  
I couldn't find it in the [GBIF checklists catalogue](https://www.gbif.org/dataset/search?type=CHECKLIST).
Are there any [plans of publishing this to GBIF](https://github.com/gbif/portal-feedback/issues/3210) as a _[Darwincore checklist dataset](https://www.gbif.org/dataset-classes#checklists)_?

This way everybody could easily use/browse the _[Leipzig Catalogue of Vasculare Plants](https://www.biorxiv.org/content/10.1101/2020.05.08.077149v1)_ online, not needing to download the whole dataset nor using R to resolve names.
It would also make things easier for people already used to grab taxonomical data from GBIF portal and APIs.

Thanks a lot.

**Comment by BrunoVilela** [comment]
Thanks, I will close this issue, as the LCVP have been already been published in the GBIF checklists catalogue: https://www.gbif.org/dataset/bae5856f-da10-4333-90a0-5a2135361b30
