### ISSUE TITLE
encoding and formatting issues

### ISSUE THREAD

**Issue by dpl10** [idiv-biodiversity/LCP#3]
The LCVP_104.zip file contains some encoding errors as well as some incorrectly formatted data. To correct the encoding and data errors, as best as possible, I did the following (on Ubuntu 20.04):

unzip -p LCVP_104.zip LCVP_103.txt | iconv -f iso-8859-1 -t utf-8 |
grep -v -P 'Launaea forma pulverulenta \(Rech\.f\.\) Parsa' | ### missing specific epithet; duplicate of full record 'Launaea acanthoides forma pulverulenta (Rech.f.) Parsa'?
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\x81","",line)) for line in sys.stdin]' | ### UTF8 encoding error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\x8a","Š",line)) for line in sys.stdin]' | ### UTF8 encoding error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\x8e","Ž",line)) for line in sys.stdin]' | ### UTF8 encoding error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\x9a","š",line)) for line in sys.stdin]' | ### UTF8 encoding error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Ã\x87","Ç",line)) for line in sys.stdin]' | ### UTF8 encoding error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\(\) ","",line)) for line in sys.stdin]' | ### empty parenthesis error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\(([^)]+)\)\t","\\1\t",line)) for line in sys.stdin]' | ### lone parenthetical author(s) error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\(\(Daveau ex Cout\.\) Castro\) T\.E\.Díaz & al\.","(Daveau ex Cout.) T.E.Díaz & al.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\(\(Schinz\) C\.B\.Clarke\) comb\.ined\.","(Schinz) C.B.Clarke comb.ined.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\(\(Volkens ex Gilg\) C\.B\.Clarke\) comb.ined.","(Volkens ex Gilg) C.B.Clarke comb.ined.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\(\(Volkens ex Lopr\.\) C\.B\.Clarke\) comb\.ined\.","(Volkens ex Lopr.) C.B.Clarke) comb.ined.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\(C\.B\.Clarke\) comb\.ined\.","C.B.Clarke comb.ined.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("\(Skottsb\.\)\]","(Skottsb.)",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Achillea nobilis subsp\. sipylea \(O\.Schwarz\)\]","Achillea nobilis subsp. sipylea (O.Schwarz) Bässler",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Calolisianthus purpurascens \(\(Lisianthius purpurascens Aubl\.\) Mscr\.","Lisianthius purpurascens Aubl.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Centaurea oscensis \(E\.López & Devesa\) Pau ex E\.López & Devesa\) Raab-Straube & Greuter","Centaurea oscensis (Pau ex E.López & Devesa) Raab-Straube & Greuter",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Cordyloblaste henschelii var\. maingayi \(Benth\. ex C\.B\.Clarke\) comb\.ined\.","Cordyloblaste henschelii var. maingayi Benth. ex C.B.Clarke comb.ined.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Diarthron iranicum \(Pobed\.\) KitTan \(Pobed\.\) KitTan","Diarthron iranicum (Pobed.) KitTan",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Draconopteris draconoptera \(D\.C\.Eaton\) LiBingZhang & LiangZhangDraconopteris draconoptera \(D\.C\.Eaton\) LiBingZhang & LiangZhang", "Draconopteris draconoptera (D.C.Eaton) LiBingZhang & LiangZhang",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Eleutherococcus henryi \(\(Oliv\.\) Harms\) Harms\.","Eleutherococcus henryi Oliv.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Gymnosporia verrucosa \( \(Celastrus verrucosus E.Mey\. ex Harv\. & Sond\.\) Mscr\.", "Celastrus verrucosus E.Mey. ex Harv. & Sond.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Helianthemum distachyos \(\(Roth\) Holub\) Moench","Helianthemum distachyos Moench",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Ligularia lancifera \(\(J\.R\.Drumm\.\) Grierson\) R\.C\.Srivast\. & C\.Jeffrey","Ligularia lancifera (J\.R\.Drumm\.) R\.C\.Srivast\. & C\.Jeffrey",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Marcelliopsis tomentosa \(Volkens ex Lopr\.\) C\.B\.Clarke\) comb\.ined\.","Marcelliopsis tomentosa (Volkens ex Lopr.) C.B.Clarke comb.ined.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("notho subsp\. ([a-z]+)","subsp. \\1_x",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Pseudosenegalia riograndensis \(Atahuachi & L\.Rico\) ","Pseudosenegalia riograndensis (Atahuachi & L.Rico) Seigler & Ebinger",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Rosa marginata var\. hampeana \(Griseb\.\) ex Crép\.\) Brumme & Gladis","Rosa marginata var. hampeana (Griseb. ex Crép.) Brumme & Gladis",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Santalum insulare var\. marchionense \(Skottsb\.\)","Santalum insulare var. marchionense Skottsb.",line)) for line in sys.stdin]' | ### author formatting error
python3 -c 'import sys,re;[sys.stdout.write(re.sub("Wurfbainia villosa var\. xanthioides \(\(Wall\. ex Baker\) T\.L\.Wu & S\.J\.Chen\) Škornick\. & A\.D\.Poulsen","Wurfbainia villosa var. xanthioides (Wall. ex Baker) Škornick. & A.D.Poulsen",line)) for line in sys.stdin]' | ### author formatting error
xz -9 > LCVP-1.03-UTF8.tsv.xz

I am not sure that all of these corrections are the right thing to do. I only checked the specific author formatting errors against IPNI, the Plant List, and a few other sources. I did not check the empty parenthesis (n=15) or lone parenthetical author(s) (n=215) errors (these are likely missing data rather than stray punctuation and thus these fixes are, at best, incomplete solutions). In any event, the targeted entries should be reexamined and updated.

**Comment by BrunoVilela** [comment]
Thanks for pointing this error dpl10. The new package version checks for invalid characters in both LCVP and users data.
