### ISSUE TITLE
"Output Taxon" entries that are not in "Input Taxon" entries

### ISSUE THREAD

**Issue by dimus** [idiv-biodiversity/LCP#4]
Some "Output Taxon" entreis given in the LCVP_104.zip are not found in "Input Taxon". It seems that some of them are lexical variants, others are not present. I am attaching a list of such name-strings.

[no-input-name.txt](https://github.com/idiv-biodiversity/LCVP/files/7793839/no-input-name.txt)

**Comment by BrunoVilela** [comment]
Hi dimus, thanks for pointing this out. Now, the updated version (LCVP v3.0) includes all the "Output Taxon" in the "Input Taxon".
