### ISSUE TITLE
Problem with encoding of letter Š in species Silene bazardzica Šourková

### ISSUE THREAD

**Issue by elisabeth-huellbusch** [idiv-biodiversity/LCP#6]
The author for "Silene bazardzica" is not correct in the data.
Here's my code and the result:
```R
library(LCVP)
data(tab_lcvp)
tab_lcvp[grep("Silene baz", tab_lcvp$Output.Taxon),]
#        global.Id Input.Genus Input.Epitheton    Rank Input.Subspecies.Epitheton               Input.Authors
# 882415     870763      Otites      bazardzica species                        nil (<U+008A>ourková) Chrtek.f.
# 1164860   1150141      Silene      bazardzica species                        nil             <U+008A>ourková
#           Status globalId.of.Output.Taxon                       Output.Taxon          Family          Order
# 882415   synonym                  1150141 Silene bazardzica <U+008A>ourková  Caryophyllaceae Caryophyllales
# 1164860 accepted                  1150141 Silene bazardzica <U+008A>ourková  Caryophyllaceae Caryophyllales
#         Literature Comments
# 882415                     
# 1164860    
```
Instead of <U+008A> it should be Š - see "Silene bazardzica [Šourková](https://www.ipni.org/a/9923-1)" (https://www.ipni.org/n/982834-1). 

Note: Since the LCVP data has been integrated into GBIF, there is now a subspecies "Silene bazardzica subsp. ourková" https://www.gbif.org/species/11207632, which is apparently wrong. Can you fix this a) in the data for the package, b) is there a way to fix that on GBIF subsequently?

I haven't checked whether there are further problems with encoding.

**Comment by BrunoVilela** [comment]
Hi Elisabeth, thanks for reporting this issue. It has now been fixed in the package. I will contact the team to modify it on GBIF.

**Comment by elisabeth-huellbusch** [comment]
Thank you!
